# Generated by Django 2.2 on 2021-12-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pynotify', '0007_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotificationtemplate',
            name='trigger_action_alternative',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='trigger action alternative'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='trigger_action_alternative',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='trigger action alternative'),
        ),
        migrations.AlterField(
            model_name='adminnotificationtemplate',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='is locked'),
        ),
    ]
